# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-29 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(editable=False, unique=True),
        ),
    ]
