# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-29 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameTracker', '0002_auto_20190929_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
