# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-01 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameTracker', '0003_auto_20190929_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
