# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-01 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameTracker', '0004_auto_20191001_0131'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playedgame',
            unique_together=set([('event', 'game')]),
        ),
    ]
