# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-01 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameTracker', '0005_auto_20191001_0203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
    ]
