# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameTracker', '0009_auto_20191008_0248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='event',
            name='player_count',
            field=models.PositiveSmallIntegerField(verbose_name='Number of Participants'),
        ),
        migrations.AlterField(
            model_name='game',
            name='in_library',
            field=models.BooleanField(default=True, verbose_name='In Demo Library'),
        ),
    ]
