# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-24 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameTracker', '0010_auto_20191012_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playedgame',
            options={'ordering': ['event', 'game']},
        ),
    ]
